language: node_js

node_js:
  - "node"

install:
  - npm install

script: 
  - rm -rf dist && npm run build

deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  name: eward
  keep-history: true
  on:
    branch: master